apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  namespace: {{ .Values.namespace }}
  labels:
    app: training-k8s
    tier: api
spec:
  selector:
    matchLabels:
      app: training-k8s
      tier: api
  template:
    metadata:
      labels:
        app: training-k8s
        tier: api
    spec:
      initContainers:
      - name: init-wait-db
        image: mysql
        command: ["mysqladmin","ping","-h", {{ .Values.bdd.serviceName }}]
      containers:
      - name: tutoapi-img
        image: samiamr/api-k8s
        imagePullPolicy: Always
        env:
        - name: MYSQL_HOST
          value: {{ .Values.bdd.serviceName }}
        - name: MYSQL_USER
          value: {{ .Values.database.username | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.database.password | b64enc | quote }}
        - name: MYSQL_DATABASE
          value: workshop
      dnsPolicy: ClusterFirst
