apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.hostIngressName }}.projet-davidson.fr
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: {{ .Values.api.serviceName }} 
          servicePort: {{ .Values.api.port }}
