kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.bdd.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: training-k8s
    tier: bdd
spec:
  type: ClusterIP
  selector:
    app: training-k8s
    tier: bdd
  ports:
  - protocol: TCP
    port: {{ .Values.bdd.port }}
    targetPort: {{ .Values.bdd.port }}
