kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.api.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: training-k8s
    tier: api
spec:
  type: ClusterIP
  selector:
    app: training-k8s
    tier: api
  ports:
  - protocol: TCP
    port: {{ .Values.api.port }}
